# Generated by Django 3.2.9 on 2021-12-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_follow_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_picture',
            field=models.ImageField(blank=True, default='default_banner/default_banner.png', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_pp/default_pp.jpg', null=True, upload_to='profile-pictures/'),
        ),
    ]
